# Setup
title:               Joe Clayton
# tagline:             
description:         "Joe Clayton's Website"
url:                 'https://joeclayton13.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

markdown: CommonMarkGhPages

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
